version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: partition_db
    ports:
      - "5433:5432"
    networks:
      - partition_net

  pgadmin_partitions:
    image: dpage/pgadmin4
    container_name: pgadmin_partitions
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - partition_net

networks:
  partition_net:
    driver: bridge
